//hello from main
var links = [
    <a class="nav-link" href="index.html">Welcome</a>, 
    <a class="nav-link" href="quickstart.html">Quick Start</a>, 
    <a class="nav-link" href="about.html">About Nuvolaris</a>, 
    <a class="nav-link" href="whats-new.html">What’s New?</a>, 
    <a class="nav-link" href="mastrogpt/index.html">🚧 MastroGPT</a>, 
    <a class="nav-link" href="mastrogpt/environment.html">🚧 Environment</a>, 
    <a class="nav-link" href="mastrogpt/devel.html">🚧 Development</a>, 
    <a class="nav-link" href="mastrogpt/deploy.html">🚧 Deployment</a>, 
    <a class="nav-link" href="tutorial/index.html">Tutorial</a>, 
    <a class="nav-link" href="tutorial/getting-started.html">Getting Started</a>, 
    <a class="nav-link" href="tutorial/first-steps.html">First Steps</a>, 
    <a class="nav-link" href="tutorial/form-validation.html">Form Validation</a>, 
    <a class="nav-link" href="tutorial/use-database.html">Use Database</a>, 
    <a class="nav-link" href="tutorial/notify-message.html">Sending Notifications</a>, 
    <a class="nav-link" href="tutorial/packaging.html">App Deployment</a>, 
    <a class="nav-link" href="development/index.html">Development</a>, 
    <a class="nav-link" href="development/index-entities.html">Entities</a>, 
    <a class="nav-link" href="development/actions.html">Actions</a>, 
    <a class="nav-link" href="development/webactions.html">Web Actions</a>, 
    <a class="nav-link" href="development/parameters.html">Parameters</a>, 
    <a class="nav-link" href="development/annotations.html">Annotations</a>, 
    <a class="nav-link" href="development/scheduler.html">Scheduler</a>, 
    <a class="nav-link" href="development/packages.html">Packages</a>, 
    <a class="nav-link" href="development/feeds.html">Feeds</a>, 
    <a class="nav-link" href="development/index-runtimes.html">Runtimes</a>, 
    <a class="nav-link" href="development/actions-nodejs.html">🚧 Node</a>, 
    <a class="nav-link" href="development/actions-python.html">🚧 Python</a>, 
    <a class="nav-link" href="development/actions-go.html">🚧 Go</a>, 
    <a class="nav-link" href="development/actions-java.html">🚧 Java</a>, 
    <a class="nav-link" href="development/actions-php.html">🚧 PHP</a>, 
    <a class="nav-link" href="development/index-references.html">References</a>, 
    <a class="nav-link" href="development/rest_api.html">Rest API</a>, 
    <a class="nav-link" href="development/scheduler.html">Scheduler</a>, 
    <a class="nav-link" href="development/cli.html">Advanced CLI</a>, 
    <a class="nav-link" href="development/reference.html">Naming and Limits</a>, 
    <a class="nav-link" href="development/actions-new.html">Runtimes under the hood</a>, 
    <a class="nav-link" href="development/actions-actionloop.html">Building your runtime</a>, 
    <a class="nav-link" href="cli/index.html">CLI</a>, 
    <a class="nav-link" href="cli/entities.html">Entities</a>, 
    <a class="nav-link" href="cli/packages.html">Packages</a>, 
    <a class="nav-link" href="cli/actions.html">Actions</a>, 
    <a class="nav-link" href="cli/activations.html">Activations</a>, 
    <a class="nav-link" href="cli/sequences.html">Sequences</a>, 
    <a class="nav-link" href="cli/triggers.html">Triggers</a>, 
    <a class="nav-link" href="cli/rules.html">Rules</a>, 
    <a class="nav-link" href="cli/project.html">🚧 Project</a>, 
    <a class="nav-link" href="cli/admin.html">Administration</a>, 
    <a class="nav-link" href="cli/debug.html">Debugging</a>, 
    <a class="nav-link" href="installation/index.html">Installation</a>, 
    <a class="nav-link" href="installation/download.html">Download</a>, 
    <a class="nav-link" href="installation/prereq.html">Prerequisites</a>, 
    <a class="nav-link" href="installation/prereq-docker.html">Local Docker</a>, 
    <a class="nav-link" href="installation/prereq-server-generic.html">SSH and Sudo</a>, 
    <a class="nav-link" href="installation/prereq-server-aws.html"> Server on AWS</a>, 
    <a class="nav-link" href="installation/prereq-server-gcp.html">Server on GCP</a>, 
    <a class="nav-link" href="installation/prereq-k3s.html">Install K3S</a>, 
    <a class="nav-link" href="installation/prereq-mk8s.html">Install MicroK8S</a>, 
    <a class="nav-link" href="installation/prereq-kubernetes.html">Kubernetes Cluster</a>, 
    <a class="nav-link" href="installation/prereq-eks.html">Amazon EKS</a>, 
    <a class="nav-link" href="installation/prereq-aks.html">Azure AKS</a>, 
    <a class="nav-link" href="installation/prereq-gke.html">Google GKE</a>,
    <a class="nav-link" href="installation/prereq-osh.html">RedHat OpenShift</a>, 
    <a class="nav-link" href="installation/prereq-cluster.html">Generic Kubernetes</a>, 
    <a class="nav-link" href="installation/configure.html">Configure Nuvolaris</a>, 
    <a class="nav-link" href="installation/configure-dns.html">DNS and SSL</a>, 
    <a class="nav-link" href="installation/configure-services.html">Services</a>, 
    <a class="nav-link" href="installation/install.html">Install Nuvolaris</a>, 
    <a class="nav-link" href="installation/install-local.html">Local Installation</a>, 
    <a class="nav-link" href="installation/install-server.html">Server Installation</a>, 
    <a class="nav-link" href="installation/install-cluster.html">Cluster Installation</a>, 
    <a class="nav-link" href="installation/debug.html">Troubleshooting</a>
]
//cannot find page about
